# Site settings
title: essay
title_description: 这里有诗和远方的遐想
email: mnichangxin@163.com
url: "http://mnichangxin.github.io/essay"
static_url: "/static"
github_username: mnichangxin

# Build settings
markdown: kramdown

# paginate
gems: [jekyll-paginate]
paginate: 1
paginate_path: "page:num"