# Site settings

# title
title: essay
title_description: 这里有诗和远方的遐想

# url 
baseurl: ""
url: "http://mnichangxin.github.io/essay"

# info
person_page: "http://mnichangxin.com"
github_username: mnichangxin
email: mnichangxin@163.com

# markdown setting
markdown: kramdown

# paginate
gems: [jekyll-paginate]
paginate: 1
paginate_path: "page:num"